config/routes.rb
Statistics::Engine.routes.draw do
  resources :candidates, only: :index
  resources :employers, only: :index
end

app/models/statistics/candidate.rb
module Statistics
  class Candidate < User
    default_scope { includes(:completed_interviews).where(role: 'applicant') }

    has_many :completed_interviews, 
              -> { merge(Interview.completed) },
              class_name: 'Interview', 
              inverse_of: :applicant, 
              foreign_key: :applicant_id

    def completed_interviews_amount
      completed_interviews.size
    end
  end
end

app/models/statistics/employer.rb
module Statistics
  class Employer < User
    default_scope { includes(:completed_interviews).where(role: 'employer') }

    has_many :completed_interviews, 
              -> { merge(Interview.completed) },
              class_name: 'Interview', 
              inverse_of: :applicant, 
              foreign_key: :applicant_id

    def completed_interviews_amount
      completed_interviews.size
    end
  end
end

app/controllers/statistics/candidates_controller.rb
# require_dependency "statistics/application_controller"

module Statistics
  class CandidatesController < ApplicationController
    layout 'dashboard'

    load_and_authorize_resource class: 'Statistics::Candidate'

    before_action :set_candidate, only: [:show, :edit, :update, :destroy]

    # GET /candidates
    def index
      @candidates = Candidate.all
    end

    # GET /candidates/1
    def show
    end

    # GET /candidates/new
    def new
      @candidate = Candidate.new
    end

    # GET /candidates/1/edit
    def edit
    end

    # POST /candidates
    def create
      @candidate = Candidate.new(candidate_params)

      if @candidate.save
        redirect_to @candidate, notice: 'Candidate was successfully created.'
      else
        render action: 'new'
      end
    end

    # PATCH/PUT /candidates/1
    def update
      if @candidate.update(candidate_params)
        redirect_to @candidate, notice: 'Candidate was successfully updated.'
      else
        render action: 'edit'
      end
    end

    # DELETE /candidates/1
    def destroy
      @candidate.destroy
      redirect_to candidates_url, notice: 'Candidate was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_candidate
        @candidate = Candidate.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def candidate_params
        params[:candidate]
      end
  end
end

app/controllers/statistics/employers_controller.rb
# require_dependency "statistics/application_controller"

module Statistics
  class EmployersController < ApplicationController
    layout 'dashboard'

    load_and_authorize_resource class: 'Statistics::Employer'

    before_action :set_employer, only: [:show, :edit, :update, :destroy]

    # GET /employers
    def index
      @employers = Employer.includes(:completed_interviews)
                           # .references(:interviews)
                           # .group('users.id', 'interviews.id', 'completed_interviews_users.id')
    end

    # GET /employers/1
    def show
    end

    # GET /employers/new
    def new
      @employer = Employer.new
    end

    # GET /employers/1/edit
    def edit
    end

    # POST /employers
    def create
      @employer = Employer.new(employer_params)

      if @employer.save
        redirect_to @employer, notice: 'Employer was successfully created.'
      else
        render action: 'new'
      end
    end

    # PATCH/PUT /employers/1
    def update
      if @employer.update(employer_params)
        redirect_to @employer, notice: 'Employer was successfully updated.'
      else
        render action: 'edit'
      end
    end

    # DELETE /employers/1
    def destroy
      @employer.destroy
      redirect_to employers_url, notice: 'Employer was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_employer
        @employer = Employer.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def employer_params
        params[:employer]
      end
  end
end

app/helpers/statistics/application_helper.rb
module Statistics
  module ApplicationHelper
    def method_missing(method, *args, &block)
      if method.to_s.end_with?('_path') or method.to_s.end_with?('_url')
        if main_app.respond_to?(method)
          main_app.send(method, *args)
        else
          super
        end
      else
        super
      end
    end

    def respond_to?(method)
      if method.to_s.end_with?('_path') or method.to_s.end_with?('_url')
        if main_app.respond_to?(method)
          true
        else
          super
        end
      else
        super
      end
    end
  end
end

app/helpers/statistics/candidates_helper.rb
module Statistics
  module CandidatesHelper
  end
end

app/helpers/statistics/employers_helper.rb
module Statistics
  module EmployersHelper
  end
end

app/views/statistics/candidates/_form.html.erb
<%= form_for(@candidate) do |f| %>
  <% if @candidate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@candidate.errors.count, "error") %> prohibited this candidate from being saved:</h2>

      <ul>
      <% @candidate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/statistics/candidates/edit.html.erb
<h1>Editing candidate</h1>

<%= render 'form' %>

<%= link_to 'Show', @candidate %> |
<%= link_to 'Back', candidates_path %>

app/views/statistics/candidates/index.html.erb
<h1><%= t '.header' %></h1>

<table>
  <thead>
    <tr>
      <th><%= t '.email' %></th>
      <th><%= t '.full_name' %></th>
      <th><%= t '.company_name' %></th>
      <th><%= t '.interviews_amount' %></th>
    </tr>
  </thead>

  <tbody>
    <% @candidates.each do |employer| %>
      <tr>
        <td><%= employer.email %></td>
        <td><%= employer.full_name %></td>
        <td><%= employer.company_name %></td>
        <td><%= employer.completed_interviews.size %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/statistics/candidates/new.html.erb
<h1>New candidate</h1>

<%= render 'form' %>

<%= link_to 'Back', candidates_path %>

app/views/statistics/candidates/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_candidate_path(@candidate) %> |
<%= link_to 'Back', candidates_path %>

app/views/statistics/employers/_form.html.erb
<%= form_for(@employer) do |f| %>
  <% if @employer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employer.errors.count, "error") %> prohibited this employer from being saved:</h2>

      <ul>
      <% @employer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/statistics/employers/edit.html.erb
<h1>Editing employer</h1>

<%= render 'form' %>

<%= link_to 'Show', @employer %> |
<%= link_to 'Back', employers_path %>

app/views/statistics/employers/index.html.erb
<h1><%= t '.header' %></h1>

<table>
  <thead>
    <tr>
      <th><%= t '.email' %></th>
      <th><%= t '.full_name' %></th>
      <th><%= t '.company_name' %></th>
      <th><%= t '.interviews_amount' %></th>
    </tr>
  </thead>

  <tbody>
    <% @employers.each do |employer| %>
      <tr>
        <td><%= employer.email %></td>
        <td><%= employer.full_name %></td>
        <td><%= employer.company_name %></td>
        <td><%= employer.completed_interviews.size %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/statistics/employers/new.html.erb
<h1>New employer</h1>

<%= render 'form' %>

<%= link_to 'Back', employers_path %>

app/views/statistics/employers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_employer_path(@employer) %> |
<%= link_to 'Back', employers_path %>